### ISSUE TITLE
Miner plots unsigned and Undistribute Mined 0.00000000 

### ISSUE THREAD

**Issue by ronaldolemos** [hpool-dev/chia-miner#312]
Anyone know about it? Since yesterday i have none plots signed...

![image](https://user-images.githubusercontent.com/84246392/118374611-81f3f180-b593-11eb-8163-ad90daaf2cd7.png)

**Comment by h9-dev** [comment]
Please commit to signature by `0xa155***`.

**Comment by ronaldolemos** [comment]
> Please commit to signature by `0xa155***`.

I dont understand, what my problem?... i have 2tb+ already and i got 0,0 chias!

**Comment by h9-dev** [comment]
Unsigned plot file cannot participate in the work and will not be profitable. Even solo is the same.

**Comment by cdeniz** [comment]
I have same problem.

**Comment by AloeKing** [comment]
Are you mining with the wallet you have created those plots with? Do you mix plots from more than 2 wallets into one miner?

**Comment by Bunnykiller151** [comment]
@AloeKing  thank you for being in every post but what exaclty should go wrong if we mix hose plots?

**Comment by AloeKing** [comment]
I have no idea why but I have done it myself during last week and I was getting no reward because of it. So I have sorted out the plots to different directories and I am running hpool miner for each of them. Now all of my plots are signed except for one which I have no idea why it is not working and I am also getting correct rewards.

**Comment by Bunnykiller151** [comment]
I see man, thank you for sharing your experience. Thats acutally new, since i have run plots made from different wallets be4. Anyway, to add new wallets i need that sms verification thing to work, how did you manage this? somehow i dont receive any sms.

**Comment by AloeKing** [comment]
I do believe we misunderstood. You dont need to add wallet addresses but the signatures from them. 

![image](https://user-images.githubusercontent.com/83868735/118392226-cd141000-b638-11eb-80f4-929e1f199ad7.png)

About the SMS I have no idea if its working now, I have set it up 2 weeks ago together with google verification and since then i didnt need it, also my XCH reward is not high enough to be withdrawn from the hpool yet. I am gonna make a new XCH wallet now and try to add address whether it working for me or no.

**Comment by AloeKing** [comment]
I only do need google verification code for adding addresses.

![image](https://user-images.githubusercontent.com/83868735/118392393-dbaef700-b639-11eb-8c43-bd33f6f086c6.png)

![image](https://user-images.githubusercontent.com/83868735/118392421-f4b7a800-b639-11eb-99c2-d4f862e29c63.png)

**Comment by ronaldolemos** [comment]
I open firewall W10 and add new signature  PC
