### ISSUE TITLE
hidden fee 70%?

### ISSUE THREAD

**Issue by mrfectum** [hpool-dev/chia-miner#477]
When I set the daily income hidden fee to 20%, it never gives the correct one. Incoming I need to set 70% to be correct. is this true ? I'm starting to regret joining hpool. If there is an error it needs to be fixed

There is no problem in the miner.

**daily income**

![hpool4](https://user-images.githubusercontent.com/84762114/119443471-58289080-bd32-11eb-8caa-79206abf8080.png)

**%20 hidden fee**

![hpool3](https://user-images.githubusercontent.com/84762114/119443479-5a8aea80-bd32-11eb-898a-0c82199df8a3.png)

**%70 hidden fee**

![hpool70](https://user-images.githubusercontent.com/84762114/119443992-3085f800-bd33-11eb-8300-f72eda3be711.png)

![hpoolminer1](https://user-images.githubusercontent.com/84762114/119443494-5f4f9e80-bd32-11eb-8a5f-a7153dcb15ba.png)

**hpool miner**

![hpoolminer](https://user-images.githubusercontent.com/84762114/119444101-5f9c6980-bd33-11eb-9730-c1db26ad9eb5.png)

**Comment by AndyX-Net** [comment]
That's true.

**Comment by Zicaleo** [comment]
It looks like the calculator simply dividing the monthly XCH to get the daily XCH, which means, it is your average daily earning across a month from now, rather than the your first day (i.e. today) earning, since it will take your future 300 plots in to account.
To get a more accurate today earning, I think you should set your plotting power to 0, it will underestimate your monthly earning, but should be align with what you earn today.

I have 98 plots atm which is similar to you, got 0.0071 XCH yesterday, and calculator estimate 0.0066 daily rate.
![圖片](https://user-images.githubusercontent.com/5187707/119608773-19c1cd00-be29-11eb-9fdd-3368842b7c22.png)
![圖片](https://user-images.githubusercontent.com/5187707/119608818-2c3c0680-be29-11eb-9d96-a0471e4c0f87.png)
![圖片](https://user-images.githubusercontent.com/5187707/119608853-3958f580-be29-11eb-95fa-7cb9a0bcb0e8.png)
![圖片](https://user-images.githubusercontent.com/5187707/119608866-3f4ed680-be29-11eb-90b9-d1da8efd0f43.png)

Btw your contribution chart jumping up and down... this will affect your earning, better check your miner log

**Comment by mrfectum** [comment]
thank you for the answer. After resetting the server, the contribution chart has become stable.
have a good day
