### ISSUE TITLE
Hpool gui and hpool console

### ISSUE THREAD

**Issue by tokenhoki** [hpool-dev/chia-miner#524]
we must run both? gui and console  or just run gui / console?

**Comment by Gokuref** [comment]
You can choose which one suits you better.
I was using gui with one pc, but since I have a few hds connected in 4 pcs, I'd rather using console to see if it's all running with "info" or "debug". Also console can be used to choose paths that gui don't, atleast for me, gui didn't reconized some paths, I'm not sure why.

**Comment by tokenhoki** [comment]
aha ic, thanks . yes gui didnt reconized some path, but hashrate high(i mean capacity ) then console. idk why
