### ISSUE TITLE
hpool does not work

### ISSUE THREAD

**Issue by chiabro23** [hpool-dev/chia-miner#531]
hi Guys,
I get the message that I should try again later, is that normal, or is it the same for you?

**Comment by turgutcaa** [comment]
> hi Guys,
> I get the message that I should try again later, is that normal, or is it the same for you?

He still writes 'auditing'. I guess it won't improve. It would be wise to switch to solo mining.

**Comment by szamaq** [comment]
Yep, it looks like they finished with hpool project. But they are not going to tell us it for sure. Absolutely no feeding us with any information looks like they abandoned us.

But solo mining means you won`t get any chia ever. Because if (for example) you may get it after 2 months ... you wont. Because network grown up so it will change from 2 months to 3, 4, 5. This is why this coin WAS worth mining solo some time ago.
